# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - webComments

on:
  push:
    branches:
      - master
    paths:
      - 'host.json'
      - 'package.json'
      - 'package-lock.json'
      - 'src/functions/**'
      - '.github/workflows/master_webcomments.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.azure-function-package'
  NODE_VERSION: '20.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Prepare Azure Function Package'
        shell: pwsh
        run: |
          $packagePath = '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          if (Test-Path $packagePath) {
            Remove-Item -Recurse -Force $packagePath
          }
          New-Item -ItemType Directory -Path $packagePath | Out-Null
          New-Item -ItemType Directory -Path "$packagePath/src" | Out-Null
          Copy-Item host.json $packagePath
          Copy-Item package.json $packagePath
          Copy-Item package-lock.json $packagePath
          Copy-Item -Recurse src/functions "$packagePath/src/functions"

      - name: 'Resolve Project Dependencies Using Npm'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm ci --omit=dev
          npm run build --if-present
          npm run test --if-present
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'webComments'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8E0631D0B62240329443D5694F15D707 }}
